[project]
name = "auto-setup"
version = "0.0.1" 
description = "Minimal Ansible project to manage personal devices"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "ansible==11.6.0",
    "ansible-lint",
    "pre-commit",
]
