---
- name: Update Jetson packages (NVIDIA stack and deps)
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  become: true

- name: Ensure NVIDIA JetPack meta package is present
  ansible.builtin.apt:
    name: nvidia-jetpack
    state: latest
  become: true

- name: Install jtop (jetson-stats)
  ansible.builtin.apt:
    name: jetson-stats
    state: latest
  become: true
